name: Skylord

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "skylord"

          replace: "SKYLORD-OP"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: Mellow

          commit_options: '--no-verify'

          repository: .

          commit_user_name: skylord


#Sed lifee iz alone after completing this bot i will suside
